name: Build Android

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        arch: ["aarch64"]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y glslang-tools golang-lukechampine-blake3-dev librust-blake3-dev b3sum libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libdrm-dev libx11-dev
          pip3 install meson mako ninja

      - name: Set up Android NDK
        run: |
          # Download NDK 2019 version r20
          wget https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip
          unzip android-ndk-r20-linux-x86_64.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-r20
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      - name: Build DRM
        run: |
          envsubst <android-drm-${{matrix.arch}} >build-crossfile-drm
          git clone --depth 1 https://gitlab.freedesktop.org/mesa/drm.git
          cd drm
          meson setup "build-android" \
            --prefix=/tmp/drm-static \
            --cross-file "../build-crossfile-drm" \
            -Ddefault_library=static \
            -Dintel=disabled \
            -Dradeon=disabled \
            -Damdgpu=disabled \
            -Dnouveau=disabled \
            -Dvmwgfx=disabled \
            -Dfreedreno=disabled \
            -Dvc4=disabled \
            -Detnaviv=disabled
          ninja -C "build-android" install
          cd ..

      - name: Build Unified Mesa Project
        run: |
          cp android-* .
          envsubst <android-${{matrix.arch}} >build-crossfile
          meson setup "build-android" \
            --prefix=/tmp/pan \
            --cross-file "build-crossfile" \
            -Dplatforms=android \
            -Dplatform-sdk-version=26 \
            -Dllvm=disabled \
            -Dosmesa=true \
            -Degl=disabled \
            -Dopengl=true \
            -Dglx=disabled \
            -Dvulkan-drivers= \
            -Dgallium-drivers=panfrost \
            -Dbuildtype=release
          ninja -C "build-android" install

      - name: Upload Libraries
        uses: actions/upload-artifact@v4
        with:
          name: panfrost_${{matrix.arch}}
          path: /tmp/pan
